### ISSUE TITLE
Time to build a new version?

### ISSUE THREAD

**Issue by fidian** [acss-io/acss-browser#1]
When I pull down the latest version, it appears that some Atomic CSS classes are not available. For instance, `Rsz(b)` does not get applied to elements.

Is it time to just perform a build and release the module again?

**Comment by fidian** [comment]
It's been a long time and no updates. Any chance this project can get rebuilt with the latest Atomizer code?

**Comment by fidian** [comment]
Is there a way I can possibly get someone to make a new build?

**Comment by whmountains** [comment]
Hello there.  I haven't used ACSS in years.  (switched to Tailwind)  I'm afraid this project is unmaintained for the time being.

**Comment by fidian** [comment]
I don't see a new version published, but the issue was closed as completed. Was this in error?

If you're not interested in maintaining this project, are you interested in passing it to someone else?

As an aside, it appears that Tailwind fits the same niche as ACSS. What do you like more about the other approach?

**Comment by whmountains** [comment]
I'd be happy to pass along maintainership to another qualified individual.

ACSS was ahead of its time and played an important role in showing that utility classes are the way to go.  I'm not sure Tailwind would have become so popular so quickly if it had not been for ACSS.

These days I have a hard time seeing a place for ACSS.  Tailwind is vastly more popular and does everything that ACSS does and more.  For a while it was hard to put arbitrary values in tailwind classes, but with JIT that is no longer an issue.  To give you an idea of the popularity difference, acss-browser has one GitHub star, while the equivalent project in the Tailwind ecosystem (`twind`) has 2.7k.

I also have a personal preference for the way Tailwind encourages you to use a smaller number of predefined values for spacing, font-size, colors, and so on.  ACSS supports that too, but it starts from the other end having you hardcode values by default and only giving you the predefined values if you take the time to write them out.
